name: verifyme
description: "An authenticator app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: 
  get: 
  get_storage:
  path_provider:
  otp:
  base32:
  cupertino_icons: 
  mobile_scanner: 
  permission_handler:
  file_picker: 
  flutter_localizations: 
    sdk: flutter
  intl: 
  flutter_colorpicker: 
  webdav_client: 
  flutter_secure_storage: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 


flutter:

  uses-material-design: true

  generate: true